# Form implementation generated from reading ui file 'C:\Users\School Account\Projects\Wordle\wordle.ui'
# Encapsulates a main window

from PyQt5 import QtCore, QtGui, QtWidgets


class UiMainWindow(object):
    def setup_ui(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(310, 460)
        main_window.setAutoFillBackground(False)
        main_window.setStyleSheet("")
        main_window.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        main_window.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")
        # TODO: Refactor charboxes
        self.char_box_a1 = QtWidgets.QLabel(self.central_widget)
        self.char_box_a1.setGeometry(QtCore.QRect(10, 10, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_a1.setFont(font)
        self.char_box_a1.setAutoFillBackground(False)
        self.char_box_a1.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_a1.setText("")
        self.char_box_a1.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_a1.setObjectName("char_box_a1")
        self.char_box_a2 = QtWidgets.QLabel(self.central_widget)
        self.char_box_a2.setGeometry(QtCore.QRect(70, 10, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_a2.setFont(font)
        self.char_box_a2.setAutoFillBackground(False)
        self.char_box_a2.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_a2.setText("")
        self.char_box_a2.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_a2.setObjectName("char_box_a2")
        self.char_box_a3 = QtWidgets.QLabel(self.central_widget)
        self.char_box_a3.setGeometry(QtCore.QRect(130, 10, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_a3.setFont(font)
        self.char_box_a3.setAutoFillBackground(False)
        self.char_box_a3.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_a3.setText("")
        self.char_box_a3.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_a3.setObjectName("char_box_a3")
        self.char_box_a4 = QtWidgets.QLabel(self.central_widget)
        self.char_box_a4.setGeometry(QtCore.QRect(190, 10, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_a4.setFont(font)
        self.char_box_a4.setAutoFillBackground(False)
        self.char_box_a4.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_a4.setText("")
        self.char_box_a4.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_a4.setObjectName("char_box_a4")
        self.char_box_a5 = QtWidgets.QLabel(self.central_widget)
        self.char_box_a5.setGeometry(QtCore.QRect(250, 10, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_a5.setFont(font)
        self.char_box_a5.setAutoFillBackground(False)
        self.char_box_a5.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_a5.setText("")
        self.char_box_a5.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_a5.setObjectName("char_box_a5")
        self.char_box_b4 = QtWidgets.QLabel(self.central_widget)
        self.char_box_b4.setGeometry(QtCore.QRect(190, 70, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_b4.setFont(font)
        self.char_box_b4.setAutoFillBackground(False)
        self.char_box_b4.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_b4.setText("")
        self.char_box_b4.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_b4.setObjectName("char_box_b4")
        self.char_box_b1 = QtWidgets.QLabel(self.central_widget)
        self.char_box_b1.setGeometry(QtCore.QRect(10, 70, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_b1.setFont(font)
        self.char_box_b1.setAutoFillBackground(False)
        self.char_box_b1.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_b1.setText("")
        self.char_box_b1.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_b1.setObjectName("char_box_b1")
        self.char_box_b3 = QtWidgets.QLabel(self.central_widget)
        self.char_box_b3.setGeometry(QtCore.QRect(130, 70, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_b3.setFont(font)
        self.char_box_b3.setAutoFillBackground(False)
        self.char_box_b3.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_b3.setText("")
        self.char_box_b3.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_b3.setObjectName("char_box_b3")
        self.char_box_b2 = QtWidgets.QLabel(self.central_widget)
        self.char_box_b2.setGeometry(QtCore.QRect(70, 70, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_b2.setFont(font)
        self.char_box_b2.setAutoFillBackground(False)
        self.char_box_b2.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_b2.setText("")
        self.char_box_b2.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_b2.setObjectName("char_box_b2")
        self.char_box_b5 = QtWidgets.QLabel(self.central_widget)
        self.char_box_b5.setGeometry(QtCore.QRect(250, 70, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_b5.setFont(font)
        self.char_box_b5.setAutoFillBackground(False)
        self.char_box_b5.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_b5.setText("")
        self.char_box_b5.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_b5.setObjectName("char_box_b5")
        self.char_box_c1 = QtWidgets.QLabel(self.central_widget)
        self.char_box_c1.setGeometry(QtCore.QRect(10, 130, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_c1.setFont(font)
        self.char_box_c1.setAutoFillBackground(False)
        self.char_box_c1.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_c1.setText("")
        self.char_box_c1.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_c1.setObjectName("char_box_c1")
        self.char_box_c4 = QtWidgets.QLabel(self.central_widget)
        self.char_box_c4.setGeometry(QtCore.QRect(190, 130, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_c4.setFont(font)
        self.char_box_c4.setAutoFillBackground(False)
        self.char_box_c4.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_c4.setText("")
        self.char_box_c4.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_c4.setObjectName("char_box_c4")
        self.char_box_c5 = QtWidgets.QLabel(self.central_widget)
        self.char_box_c5.setGeometry(QtCore.QRect(250, 130, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_c5.setFont(font)
        self.char_box_c5.setAutoFillBackground(False)
        self.char_box_c5.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_c5.setText("")
        self.char_box_c5.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_c5.setObjectName("char_box_c5")
        self.char_box_c2 = QtWidgets.QLabel(self.central_widget)
        self.char_box_c2.setGeometry(QtCore.QRect(70, 130, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_c2.setFont(font)
        self.char_box_c2.setAutoFillBackground(False)
        self.char_box_c2.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_c2.setText("")
        self.char_box_c2.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_c2.setObjectName("char_box_c2")
        self.char_box_c3 = QtWidgets.QLabel(self.central_widget)
        self.char_box_c3.setGeometry(QtCore.QRect(130, 130, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_c3.setFont(font)
        self.char_box_c3.setAutoFillBackground(False)
        self.char_box_c3.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_c3.setText("")
        self.char_box_c3.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_c3.setObjectName("char_box_c3")
        self.char_box_d3 = QtWidgets.QLabel(self.central_widget)
        self.char_box_d3.setGeometry(QtCore.QRect(130, 190, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_d3.setFont(font)
        self.char_box_d3.setAutoFillBackground(False)
        self.char_box_d3.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_d3.setText("")
        self.char_box_d3.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_d3.setObjectName("char_box_d3")
        self.char_box_d1 = QtWidgets.QLabel(self.central_widget)
        self.char_box_d1.setGeometry(QtCore.QRect(10, 190, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_d1.setFont(font)
        self.char_box_d1.setAutoFillBackground(False)
        self.char_box_d1.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_d1.setText("")
        self.char_box_d1.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_d1.setObjectName("char_box_d1")
        self.char_box_d5 = QtWidgets.QLabel(self.central_widget)
        self.char_box_d5.setGeometry(QtCore.QRect(250, 190, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_d5.setFont(font)
        self.char_box_d5.setAutoFillBackground(False)
        self.char_box_d5.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_d5.setText("")
        self.char_box_d5.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_d5.setObjectName("char_box_d5")
        self.char_box_d2 = QtWidgets.QLabel(self.central_widget)
        self.char_box_d2.setGeometry(QtCore.QRect(70, 190, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_d2.setFont(font)
        self.char_box_d2.setAutoFillBackground(False)
        self.char_box_d2.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_d2.setText("")
        self.char_box_d2.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_d2.setObjectName("char_box_d2")
        self.char_box_d4 = QtWidgets.QLabel(self.central_widget)
        self.char_box_d4.setGeometry(QtCore.QRect(190, 190, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_d4.setFont(font)
        self.char_box_d4.setAutoFillBackground(False)
        self.char_box_d4.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_d4.setText("")
        self.char_box_d4.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_d4.setObjectName("char_box_d4")
        self.char_box_e5 = QtWidgets.QLabel(self.central_widget)
        self.char_box_e5.setGeometry(QtCore.QRect(250, 250, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_e5.setFont(font)
        self.char_box_e5.setAutoFillBackground(False)
        self.char_box_e5.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_e5.setText("")
        self.char_box_e5.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_e5.setObjectName("char_box_e5")
        self.char_box_e2 = QtWidgets.QLabel(self.central_widget)
        self.char_box_e2.setGeometry(QtCore.QRect(70, 250, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_e2.setFont(font)
        self.char_box_e2.setAutoFillBackground(False)
        self.char_box_e2.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_e2.setText("")
        self.char_box_e2.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_e2.setObjectName("char_box_e2")
        self.char_box_e4 = QtWidgets.QLabel(self.central_widget)
        self.char_box_e4.setGeometry(QtCore.QRect(190, 250, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_e4.setFont(font)
        self.char_box_e4.setAutoFillBackground(False)
        self.char_box_e4.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_e4.setText("")
        self.char_box_e4.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_e4.setObjectName("char_box_e4")
        self.char_box_e3 = QtWidgets.QLabel(self.central_widget)
        self.char_box_e3.setGeometry(QtCore.QRect(130, 250, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_e3.setFont(font)
        self.char_box_e3.setAutoFillBackground(False)
        self.char_box_e3.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_e3.setText("")
        self.char_box_e3.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_e3.setObjectName("char_box_e3")
        self.char_box_e1 = QtWidgets.QLabel(self.central_widget)
        self.char_box_e1.setGeometry(QtCore.QRect(10, 250, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_e1.setFont(font)
        self.char_box_e1.setAutoFillBackground(False)
        self.char_box_e1.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_e1.setText("")
        self.char_box_e1.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_e1.setObjectName("char_box_e1")
        self.char_box_f3 = QtWidgets.QLabel(self.central_widget)
        self.char_box_f3.setGeometry(QtCore.QRect(130, 310, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_f3.setFont(font)
        self.char_box_f3.setAutoFillBackground(False)
        self.char_box_f3.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_f3.setText("")
        self.char_box_f3.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_f3.setObjectName("char_box_f3")
        self.char_box_f1 = QtWidgets.QLabel(self.central_widget)
        self.char_box_f1.setGeometry(QtCore.QRect(10, 310, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_f1.setFont(font)
        self.char_box_f1.setAutoFillBackground(False)
        self.char_box_f1.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_f1.setText("")
        self.char_box_f1.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_f1.setObjectName("char_box_f1")
        self.char_box_f5 = QtWidgets.QLabel(self.central_widget)
        self.char_box_f5.setGeometry(QtCore.QRect(250, 310, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_f5.setFont(font)
        self.char_box_f5.setAutoFillBackground(False)
        self.char_box_f5.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_f5.setText("")
        self.char_box_f5.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_f5.setObjectName("char_box_f5")
        self.char_box_f2 = QtWidgets.QLabel(self.central_widget)
        self.char_box_f2.setGeometry(QtCore.QRect(70, 310, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_f2.setFont(font)
        self.char_box_f2.setAutoFillBackground(False)
        self.char_box_f2.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_f2.setText("")
        self.char_box_f2.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_f2.setObjectName("char_box_f2")
        self.char_box_f4 = QtWidgets.QLabel(self.central_widget)
        self.char_box_f4.setGeometry(QtCore.QRect(190, 310, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.char_box_f4.setFont(font)
        self.char_box_f4.setAutoFillBackground(False)
        self.char_box_f4.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.char_box_f4.setText("")
        self.char_box_f4.setAlignment(QtCore.Qt.AlignCenter)
        self.char_box_f4.setObjectName("char_box_f4")
        self.enter_button = QtWidgets.QPushButton(self.central_widget)
        self.enter_button.setGeometry(QtCore.QRect(10, 370, 280, 50))
        self.enter_button.setObjectName("enter_button")
        main_window.setCentralWidget(self.central_widget)
        self.menu_bar = QtWidgets.QMenuBar(main_window)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 310, 26))
        self.menu_bar.setDefaultUp(False)
        self.menu_bar.setObjectName("menu_bar")
        self.file_menu = QtWidgets.QMenu(self.menu_bar)
        self.file_menu.setObjectName("file_menu")
        self.game_menu = QtWidgets.QMenu(self.menu_bar)
        self.game_menu.setObjectName("game_menu")
        self.new_game_menu = QtWidgets.QMenu(self.game_menu)
        self.new_game_menu.setObjectName("new_game_menu")
        self.settings_menu = QtWidgets.QMenu(self.menu_bar)
        self.settings_menu.setObjectName("settings_menu")
        self.about_menu = QtWidgets.QMenu(self.menu_bar)
        self.about_menu.setObjectName("about_menu")
        main_window.setMenuBar(self.menu_bar)
        self.actionExit = QtWidgets.QAction(main_window)
        self.actionExit.setObjectName("actionExit")
        self.exit_action = QtWidgets.QAction(main_window)
        self.exit_action.setObjectName("exit_action")
        self.check_streak_action = QtWidgets.QAction(main_window)
        self.check_streak_action.setObjectName("check_streak_action")
        self.add_words_action = QtWidgets.QAction(main_window)
        self.add_words_action.setObjectName("add_words_action")
        self.mode_action = QtWidgets.QAction(main_window)
        self.mode_action.setObjectName("mode_action")
        self.check_stats_action = QtWidgets.QAction(main_window)
        self.check_stats_action.setObjectName("check_stats_action")
        self.daily_game_action = QtWidgets.QAction(main_window)
        self.daily_game_action.setObjectName("daily_game_action")
        self.practice_game_action = QtWidgets.QAction(main_window)
        self.practice_game_action.setObjectName("practice_game_action")
        self.actionHow_To_Play = QtWidgets.QAction(main_window)
        self.actionHow_To_Play.setObjectName("actionHow_To_Play")
        self.actionHow_To_Play_2 = QtWidgets.QAction(main_window)
        self.actionHow_To_Play_2.setObjectName("actionHow_To_Play_2")
        self.file_menu.addAction(self.exit_action)
        self.new_game_menu.addAction(self.daily_game_action)
        self.new_game_menu.addAction(self.practice_game_action)
        self.game_menu.addAction(self.new_game_menu.menuAction())
        self.game_menu.addAction(self.check_streak_action)
        self.game_menu.addAction(self.check_stats_action)
        self.settings_menu.addAction(self.add_words_action)
        self.settings_menu.addAction(self.mode_action)
        self.about_menu.addAction(self.actionHow_To_Play)
        self.about_menu.addAction(self.actionHow_To_Play_2)
        self.menu_bar.addAction(self.file_menu.menuAction())
        self.menu_bar.addAction(self.game_menu.menuAction())
        self.menu_bar.addAction(self.settings_menu.menuAction())
        self.menu_bar.addAction(self.about_menu.menuAction())

        self.retranslate_ui(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslate_ui(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Wordle"))
        self.enter_button.setText(_translate("main_window", "Enter"))
        self.file_menu.setTitle(_translate("main_window", "File"))
        self.game_menu.setTitle(_translate("main_window", "Game"))
        self.new_game_menu.setTitle(_translate("main_window", "New Game"))
        self.settings_menu.setTitle(_translate("main_window", "Settings"))
        self.about_menu.setTitle(_translate("main_window", "Help"))
        self.actionExit.setText(_translate("main_window", "Add Words"))
        self.exit_action.setText(_translate("main_window", "Exit"))
        self.check_streak_action.setText(_translate("main_window", "Check Streak"))
        self.add_words_action.setText(_translate("main_window", "Add Words"))
        self.mode_action.setText(_translate("main_window", "Mode"))
        self.check_stats_action.setText(_translate("main_window", "Check Stats"))
        self.daily_game_action.setText(_translate("main_window", "Daily"))
        self.practice_game_action.setText(_translate("main_window", "Practice"))
        self.actionHow_To_Play.setText(_translate("main_window", "Credits"))
        self.actionHow_To_Play_2.setText(_translate("main_window", "How To Play"))


class MainWindow(QtWidgets.QMainWindow, UiMainWindow):
    def __init__(self, *args, **kwargs):
        super(MainWindow, self).__init__(*args, **kwargs)
        self.setup_ui(self)
