# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/School Account/Projects/WordleQt/addword.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiAddWordDialog(object):
    def setup_ui(self, dialog: QtWidgets.QDialog):
        dialog.setObjectName("Dialog")
        dialog.resize(400, 90)
        self.button_box = QtWidgets.QDialogButtonBox(dialog)
        self.button_box.setGeometry(QtCore.QRect(0, 50, 400, 30))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Ok | QtWidgets.QDialogButtonBox.Apply |
                                           QtWidgets.QDialogButtonBox.Cancel)
        self.button_box.setCenterButtons(True)
        self.button_box.setObjectName("button_box")
        self.label = QtWidgets.QLabel(dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.word_text_edit = QtWidgets.QPlainTextEdit(dialog)
        self.word_text_edit.setGeometry(QtCore.QRect(90, 10, 300, 30))
        self.word_text_edit.setObjectName("plainTextEdit")

        self.retranslate_ui(dialog)
        self.button_box.accepted.connect(dialog.accept)
        self.button_box.rejected.connect(dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslate_ui(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("Dialog", "Add Word"))
        self.label.setText(_translate("Dialog", "Add Word:"))
