# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'statistics.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiStatisticsDialog(object):
    def setup_ui(self, stats_dialog):
        stats_dialog.setObjectName("stats_dialog")
        stats_dialog.resize(400, 330)
        stats_dialog.setStyleSheet("")
        self.buttonBox = QtWidgets.QDialogButtonBox(stats_dialog)
        self.buttonBox.setGeometry(QtCore.QRect(310, 290, 80, 30))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.one_guess_label = QtWidgets.QLabel(stats_dialog)
        self.one_guess_label.setGeometry(QtCore.QRect(10, 10, 20, 25))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.one_guess_label.setFont(font)
        self.one_guess_label.setObjectName("one_guess_label")
        self.two_guess_label = QtWidgets.QLabel(stats_dialog)
        self.two_guess_label.setGeometry(QtCore.QRect(10, 50, 20, 25))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.two_guess_label.setFont(font)
        self.two_guess_label.setObjectName("two_guess_label")
        self.three_guess_label = QtWidgets.QLabel(stats_dialog)
        self.three_guess_label.setGeometry(QtCore.QRect(10, 90, 20, 25))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.three_guess_label.setFont(font)
        self.three_guess_label.setObjectName("three_guess_label")
        self.four_guess_label = QtWidgets.QLabel(stats_dialog)
        self.four_guess_label.setGeometry(QtCore.QRect(10, 130, 20, 25))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.four_guess_label.setFont(font)
        self.four_guess_label.setObjectName("four_guess_label")
        self.five_guess_label = QtWidgets.QLabel(stats_dialog)
        self.five_guess_label.setGeometry(QtCore.QRect(10, 170, 20, 25))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.five_guess_label.setFont(font)
        self.five_guess_label.setObjectName("five_guess_label")
        self.six_guess_label = QtWidgets.QLabel(stats_dialog)
        self.six_guess_label.setGeometry(QtCore.QRect(10, 210, 20, 25))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.six_guess_label.setFont(font)
        self.six_guess_label.setObjectName("six_guess_label")
        self.fail_label = QtWidgets.QLabel(stats_dialog)
        self.fail_label.setGeometry(QtCore.QRect(10, 250, 20, 25))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.fail_label.setFont(font)
        self.fail_label.setObjectName("fail_label")
        self.one_blank_bar = QtWidgets.QLabel(stats_dialog)
        self.one_blank_bar.setGeometry(QtCore.QRect(40, 10, 350, 25))
        self.one_blank_bar.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.one_blank_bar.setText("")
        self.one_blank_bar.setObjectName("one_blank_bar")
        self.two_blank_bar = QtWidgets.QLabel(stats_dialog)
        self.two_blank_bar.setGeometry(QtCore.QRect(40, 50, 350, 25))
        self.two_blank_bar.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.two_blank_bar.setText("")
        self.two_blank_bar.setObjectName("two_blank_bar")
        self.three_blank_bar = QtWidgets.QLabel(stats_dialog)
        self.three_blank_bar.setGeometry(QtCore.QRect(40, 90, 350, 25))
        self.three_blank_bar.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.three_blank_bar.setText("")
        self.three_blank_bar.setObjectName("three_blank_bar")
        self.four_blank_bar = QtWidgets.QLabel(stats_dialog)
        self.four_blank_bar.setGeometry(QtCore.QRect(40, 130, 350, 25))
        self.four_blank_bar.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.four_blank_bar.setText("")
        self.four_blank_bar.setObjectName("four_blank_bar")
        self.five_blank_bar = QtWidgets.QLabel(stats_dialog)
        self.five_blank_bar.setGeometry(QtCore.QRect(40, 170, 350, 25))
        self.five_blank_bar.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.five_blank_bar.setText("")
        self.five_blank_bar.setObjectName("five_blank_bar")
        self.six_blank_bar = QtWidgets.QLabel(stats_dialog)
        self.six_blank_bar.setGeometry(QtCore.QRect(40, 210, 350, 25))
        self.six_blank_bar.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.six_blank_bar.setText("")
        self.six_blank_bar.setObjectName("six_blank_bar")
        self.x_blank_bar = QtWidgets.QLabel(stats_dialog)
        self.x_blank_bar.setGeometry(QtCore.QRect(40, 250, 350, 25))
        self.x_blank_bar.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"color: white;")
        self.x_blank_bar.setText("")
        self.x_blank_bar.setObjectName("x_blank_bar")

        self.retranslateUi(stats_dialog)
        self.buttonBox.accepted.connect(stats_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(stats_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(stats_dialog)

    def retranslateUi(self, stats_dialog):
        _translate = QtCore.QCoreApplication.translate
        stats_dialog.setWindowTitle(_translate("stats_dialog", "Statistics"))
        self.one_guess_label.setText(_translate("stats_dialog", "1:"))
        self.two_guess_label.setText(_translate("stats_dialog", "2:"))
        self.three_guess_label.setText(_translate("stats_dialog", "3:"))
        self.four_guess_label.setText(_translate("stats_dialog", "4:"))
        self.five_guess_label.setText(_translate("stats_dialog", "5:"))
        self.six_guess_label.setText(_translate("stats_dialog", "6:"))
        self.fail_label.setText(_translate("stats_dialog", "X:"))
